/* Copyright (c) 2017-2026, Hans Erik Thrane */

#include <catch2/catch_all.hpp>

#include "roq/core/json/buffer_stack.hpp"

#include "roq/aster_futures/protocol/json/exchange_info_ack.hpp"

using namespace roq;
using namespace roq::aster_futures;

using namespace std::literals;

using value_type = protocol::json::ExchangeInfoAck;

// note! reduced
TEST_CASE("simple", "[json_exchange_info]") {
  auto message =
      R"({)"
      R"("timezone":"UTC",)"
      R"("serverTime":1759385623251,)"
      R"("futuresType":"U_MARGINED",)"
      R"("rateLimits":[{)"
      R"("rateLimitType":"REQUEST_WEIGHT",)"
      R"("interval":"MINUTE",)"
      R"("intervalNum":1,)"
      R"("limit":2400)"
      R"(},{)"
      R"("rateLimitType":"ORDERS",)"
      R"("interval":"MINUTE",)"
      R"("intervalNum":1,)"
      R"("limit":1200)"
      R"(},{)"
      R"("rateLimitType":"ORDERS",)"
      R"("interval":"SECOND",)"
      R"("intervalNum":10,)"
      R"("limit":300)"
      R"(})"
      R"(],)"
      R"("exchangeFilters":[],)"
      R"("assets":[{)"
      R"("asset":"USDT",)"
      R"("marginAvailable":true,)"
      R"("autoAssetExchange":"-10000")"
      R"(},{)"
      R"("asset":"BTC",)"
      R"("marginAvailable":true,)"
      R"("autoAssetExchange":"0")"
      R"(},{)"
      R"("asset":"CDL",)"
      R"("marginAvailable":true,)"
      R"("autoAssetExchange":"0")"
      R"(})"
      R"(],)"
      R"("symbols":[{)"
      R"("symbol":"ASTERUSDT",)"
      R"("pair":"ASTERUSDT",)"
      R"("contractType":"PERPETUAL",)"
      R"("deliveryDate":4133404800000,)"
      R"("onboardDate":1758178800000,)"
      R"("status":"TRADING",)"
      R"("maintMarginPercent":"12.5000",)"
      R"("requiredMarginPercent":"25.0000",)"
      R"("baseAsset":"ASTER",)"
      R"("quoteAsset":"USDT",)"
      R"("marginAsset":"USDT",)"
      R"("pricePrecision":5,)"
      R"("quantityPrecision":2,)"
      R"("baseAssetPrecision":8,)"
      R"("quotePrecision":8,)"
      R"("underlyingType":"COIN",)"
      R"("underlyingSubType":[],)"
      R"("symbolType":0,)"
      R"("tradingMode":0,)"
      R"("name":"ASTER",)"
      R"("channel":"{}",)"
      R"("sequenceNo":100,)"
      R"("settlePlan":0,)"
      R"("triggerProtect":"0.1500",)"
      R"("liquidationFee":"0.025000",)"
      R"("marketTakeBound":"0.05",)"
      R"("filters":[)"
      R"({"minPrice":"0.00010","maxPrice":"200","filterType":"PRICE_FILTER","tickSize":"0.00010"},)"
      R"({"stepSize":"0.01","filterType":"LOT_SIZE","maxQty":"1000000","minQty":"0.01"},)"
      R"({"stepSize":"0.01","filterType":"MARKET_LOT_SIZE","maxQty":"5000","minQty":"0.01"},)"
      R"({"limit":200,"filterType":"MAX_NUM_ORDERS"},)"
      R"({"limit":10,"filterType":"MAX_NUM_ALGO_ORDERS"},)"
      R"({"notional":"5","filterType":"MIN_NOTIONAL"},)"
      R"({"multiplierDown":"0.9500","multiplierUp":"1.0500","ltMultiplierDown":"0.9700","multiplierDecimal":"4","filterType":"PERCENT_PRICE","ltMultiplierUp":"1.0300"})"
      R"(],)"
      R"("orderTypes":[)"
      R"("LIMIT",)"
      R"("MARKET",)"
      R"("STOP",)"
      R"("STOP_MARKET",)"
      R"("TAKE_PROFIT",)"
      R"("TAKE_PROFIT_MARKET",)"
      R"("TRAILING_STOP_MARKET"],)"
      R"("timeInForce":["GTC",)"
      R"("IOC",)"
      R"("FOK",)"
      R"("GTX",)"
      R"("RPI",)"
      R"("HIDDEN")"
      R"(])"
      R"(},{)"
      R"("symbol":"BTCUSDT",)"
      R"("pair":"BTCUSDT",)"
      R"("contractType":"PERPETUAL",)"
      R"("deliveryDate":4133404800000,)"
      R"("onboardDate":1627628400000,)"
      R"("status":"TRADING",)"
      R"("maintMarginPercent":"2.5000",)"
      R"("requiredMarginPercent":"5.0000",)"
      R"("baseAsset":"BTC",)"
      R"("quoteAsset":"USDT",)"
      R"("marginAsset":"USDT",)"
      R"("pricePrecision":1,)"
      R"("quantityPrecision":3,)"
      R"("baseAssetPrecision":8,)"
      R"("quotePrecision":8,)"
      R"("underlyingType":"COIN",)"
      R"("underlyingSubType":[],)"
      R"("symbolType":0,)"
      R"("tradingMode":0,)"
      R"("name":"Bitcoin",)"
      R"("channel":"",)"
      R"("sequenceNo":10,)"
      R"("settlePlan":0,)"
      R"("triggerProtect":"0.0200",)"
      R"("liquidationFee":"0.025000",)"
      R"("marketTakeBound":"0.02",)"
      R"("filters":[)"
      R"({"minPrice":"1","maxPrice":"1000000","filterType":"PRICE_FILTER","tickSize":"0.1"},)"
      R"({"stepSize":"0.001","filterType":"LOT_SIZE","maxQty":"300","minQty":"0.001"},)"
      R"({"stepSize":"0.001","filterType":"MARKET_LOT_SIZE","maxQty":"20","minQty":"0.001"},)"
      R"({"limit":200,"filterType":"MAX_NUM_ORDERS"},)"
      R"({"limit":10,"filterType":"MAX_NUM_ALGO_ORDERS"},)"
      R"({"notional":"5","filterType":"MIN_NOTIONAL"},)"
      R"({"multiplierDown":"0.9800","multiplierUp":"1.0200","ltMultiplierDown":"0","multiplierDecimal":"4","filterType":"PERCENT_PRICE","ltMultiplierUp":"0"})"
      R"(],)"
      R"("orderTypes":[)"
      R"("LIMIT",)"
      R"("MARKET",)"
      R"("STOP",)"
      R"("STOP_MARKET",)"
      R"("TAKE_PROFIT",)"
      R"("TAKE_PROFIT_MARKET",)"
      R"("TRAILING_STOP_MARKET")"
      R"(],)"
      R"("timeInForce":[)"
      R"("GTC",)"
      R"("IOC",)"
      R"("FOK",)"
      R"("GTX",)"
      R"("RPI",)"
      R"("HIDDEN")"
      R"(])"
      R"(})"
      R"(])"
      R"(})";
  auto helper = [&](value_type &obj) { CHECK(obj.timezone == "UTC"sv); };
  core::json::BufferStack buffers{8192, 2};
  value_type obj{message, buffers};
  helper(obj);
}
